// reviewsData.ts
export const reviews = [
  {
    name: "Anna",
    date: "August 10, 2025",
    rating: 5,
    text: "Incredible view! Totally worth it. Everything was smooth and well-organized.",
  },
  {
    name: "Mark",
    date: "June 2, 2025",
    rating: 4,
    text: "A bit crowded, but the experience was amazing overall!",
  },
  {
    name: "Sophia",
    date: "May 14, 2025",
    rating: 5,
    text: "Loved the sunset view from the top! Staff were very kind and helpful.",
  },
  {
    name: "Liam",
    date: "March 19, 2025",
    rating: 3,
    text: "Nice experience, but long waiting time despite fast-track ticket.",
  },
  {
    name: "Olivia",
    date: "January 8, 2025",
    rating: 5,
    text: "Absolutely stunning! Highly recommend going early morning.",
  },
  {
    name: "Noah",
    date: "April 23, 2025",
    rating: 4,
    text: "The view was breathtaking, though the glass reflection made photos tricky.",
  },
  {
    name: "Emma",
    date: "July 1, 2025",
    rating: 2,
    text: "Too expensive for what it offers.",
  },
  {
    name: "Ethan",
    date: "September 2, 2025",
    rating: 1,
    text: "The weather was bad and visibility was poor.",
  },
  {
    name: "John",
    date: "September 10, 2025",
    rating: 3,
    text: "Was nice",
  },
  {
    name: "Alex",
    date: "September 14, 2025",
    rating: 5,
    text: "Liked so much",
  },
  {
    name: "Anna",
    date: "September 21, 2025",
    rating: 4,
    text: "Ok",
  },
  {
    name: "Ethan",
    date: "September 27, 2025",
    rating: 5,
    text: "The most beatiful place where i ever was",
  },
  {
    name: "John",
    date: "September 29, 2025",
    rating: 3,
    text: "Very cool, but weather was poor",
  },
  {
    name: "Kate",
    date: "September 2, 2025",
    rating: 5,
    text: "",
  },
  {
    name: "Sagar Aryal",
    rating: 5,
    date: "2024-01-15",
    text: "Exceptional quality and outstanding service. Highly recommended!",
  },
  {
    name: "Marvilous Cataluna",
    rating: 4,
    date: "2024-01-14",
    text: "Very good product with excellent features. Satisfied with my purchase.",
  },
  {
    name: "Abishek Helmu",
    rating: 5,
    date: "2024-01-13",
    text: "Absolutely fantastic! Exceeded all my expectations.",
  },
  {
    name: "Htet Htet Aung",
    rating: 4,
    date: "2024-01-12",
    text: "Reliable and efficient. Good value for money.",
  },
  {
    name: "Jissa Varghese",
    rating: 5,
    date: "2024-01-11",
    text: "Brilliant product with amazing performance. Love it!",
  },
  {
    name: "Roxanne Gonsalves",
    rating: 4,
    date: "2024-01-10",
    text: "Solid product that delivers what it promises.",
  },
  {
    name: "Jagath Chandra",
    rating: 5,
    date: "2024-01-09",
    text: "Outstanding quality and superb customer support.",
  },
  {
    name: "Sergio Kutovyi",
    rating: 4,
    date: "2024-01-08",
    text: "Great product with minor room for improvement.",
  },
  {
    name: "Eiman Alkatheeri",
    rating: 5,
    date: "2024-01-07",
    text: "Perfect in every way. Would buy again without hesitation.",
  },
  {
    name: "Ahmed Hassan",
    rating: 4,
    date: "2024-01-06",
    text: "Good product that meets expectations consistently.",
  },
  {
    name: "Fatima Almeida",
    rating: 5,
    date: "2024-01-05",
    text: "Exceptional value and premium quality. Impressed!",
  },
  {
    name: "Mohammed Rahman",
    rating: 4,
    date: "2024-01-04",
    text: "Reliable performance with good features.",
  },
  {
    name: "Aisha Khan",
    rating: 5,
    date: "2024-01-03",
    text: "Absolutely love this product! Worth every penny.",
  },
  {
    name: "Omar Farooq",
    rating: 4,
    date: "2024-01-02",
    text: "Solid build quality and good functionality.",
  },
  {
    name: "Zainab Ibrahim",
    rating: 5,
    date: "2024-01-01",
    text: "Premium quality that stands out from competitors.",
  },
  {
    name: "Khalid Mahmood",
    rating: 4,
    date: "2023-12-31",
    text: "Good product with reliable performance.",
  },
  {
    name: "Layla Abdullah",
    rating: 5,
    date: "2023-12-30",
    text: "Exceptional craftsmanship and attention to detail.",
  },
  {
    name: "Yusuf Ahmed",
    rating: 4,
    date: "2023-12-29",
    text: "Meets expectations with consistent quality.",
  },
  {
    name: "Noura Hassan",
    rating: 5,
    date: "2023-12-28",
    text: "Outstanding performance and excellent value.",
  },
  {
    name: "Tariq Malik",
    rating: 4,
    date: "2023-12-27",
    text: "Good product that delivers on its promises.",
  },
  {
    name: "Samira Khan",
    rating: 5,
    date: "2023-12-26",
    text: "Absolutely brilliant! Exceeded all expectations.",
  },
  {
    name: "Rashid Ali",
    rating: 4,
    date: "2023-12-25",
    text: "Solid performance with good build quality.",
  },
  {
    name: "Amira Said",
    rating: 5,
    date: "2023-12-24",
    text: "Premium quality that's worth the investment.",
  },
  {
    name: "Jamal Hussein",
    rating: 4,
    date: "2023-12-23",
    text: "Reliable and efficient for daily use.",
  },
  {
    name: "Salma Abadi",
    rating: 5,
    date: "2023-12-22",
    text: "Exceptional product with outstanding features.",
  },
  {
    name: "Bilal Omar",
    rating: 4,
    date: "2023-12-21",
    text: "Good value proposition with solid performance.",
  },
  {
    name: "Hana Mohamed",
    rating: 5,
    date: "2023-12-20",
    text: "Perfect product that delivers exceptional results.",
  },
  {
    name: "Karim Abdullah",
    rating: 4,
    date: "2023-12-19",
    text: "Consistently good performance and reliability.",
  },
  {
    name: "Leila Hassan",
    rating: 5,
    date: "2023-12-18",
    text: "Outstanding quality that exceeds expectations.",
  },
  {
    name: "Nasir Khan",
    rating: 4,
    date: "2023-12-17",
    text: "Good product with minor improvements possible.",
  },
  {
    name: "Yasmin Ali",
    rating: 5,
    date: "2023-12-16",
    text: "Absolutely fantastic! Highly recommended to everyone.",
  },
  {
    name: "Faisal Rahman",
    rating: 4,
    date: "2023-12-15",
    text: "Solid product that meets most requirements.",
  },
  {
    name: "Dalia Ibrahim",
    rating: 5,
    date: "2023-12-14",
    text: "Exceptional performance and premium quality.",
  },
  {
    name: "Hamza Ahmed",
    rating: 4,
    date: "2023-12-13",
    text: "Good reliable product for everyday use.",
  },
  {
    name: "Nadia Said",
    rating: 5,
    date: "2023-12-12",
    text: "Perfect in every aspect. Very satisfied!",
  },
  {
    name: "Rami Hassan",
    rating: 4,
    date: "2023-12-11",
    text: "Consistent quality with good features.",
  },
  {
    name: "Sana Khan",
    rating: 5,
    date: "2023-12-10",
    text: "Outstanding value and exceptional performance.",
  },
  {
    name: "Waleed Omar",
    rating: 4,
    date: "2023-12-09",
    text: "Good product that delivers reliable results.",
  },
  {
    name: "Lina Abdullah",
    rating: 5,
    date: "2023-12-08",
    text: "Absolutely brilliant quality and service.",
  },
  {
    name: "Adnan Malik",
    rating: 4,
    date: "2023-12-07",
    text: "Solid performance with minor enhancements needed.",
  },
  {
    name: "Mona Hassan",
    rating: 5,
    date: "2023-12-06",
    text: "Exceptional product that exceeds expectations.",
  },
  {
    name: "Tahir Ahmed",
    rating: 4,
    date: "2023-12-05",
    text: "Good reliable product for the price.",
  },
  {
    name: "Rania Khan",
    rating: 5,
    date: "2023-12-04",
    text: "Perfect quality and outstanding performance.",
  },
  {
    name: "Zayed Ibrahim",
    rating: 4,
    date: "2023-12-03",
    text: "Consistently good with reliable features.",
  },
  {
    name: "Nabil Hassan",
    rating: 5,
    date: "2023-12-02",
    text: "Absolutely love it! Worth every penny spent.",
  },
  {
    name: "Farah Omar",
    rating: 4,
    date: "2023-12-01",
    text: "Good product that meets expectations well.",
  },
  {
    name: "Samir Khan",
    rating: 5,
    date: "2023-11-30",
    text: "Exceptional quality that stands the test of time.",
  },
  {
    name: "Lamia Ahmed",
    rating: 4,
    date: "2023-11-29",
    text: "Solid performance with good build quality.",
  },
  {
    name: "Kareem Abdullah",
    rating: 5,
    date: "2023-11-28",
    text: "Outstanding product with premium features.",
  },
  {
    name: "Salim Hassan",
    rating: 4,
    date: "2023-11-27",
    text: "Reliable and efficient for regular use.",
  },
  {
    name: "Noor Khan",
    rating: 5,
    date: "2023-11-26",
    text: "Perfect in every way. Highly satisfied!",
  },
  {
    name: "Majid Omar",
    rating: 4,
    date: "2023-11-25",
    text: "Good product with consistent performance.",
  },
  {
    name: "Sahar Ibrahim",
    rating: 5,
    date: "2023-11-24",
    text: "Exceptional value and outstanding quality.",
  },
  {
    name: "Anwar Hassan",
    rating: 4,
    date: "2023-11-23",
    text: "Solid product that delivers as promised.",
  },
  {
    name: "Hassan Khan",
    rating: 5,
    date: "2023-11-22",
    text: "Absolutely brilliant! Exceeded expectations.",
  },
  {
    name: "Rasha Abdullah",
    rating: 4,
    date: "2023-11-21",
    text: "Good reliable product with minor improvements.",
  },
  {
    name: "Fahad Omar",
    rating: 5,
    date: "2023-11-20",
    text: "Exceptional performance and premium build.",
  },
  {
    name: "Mariam Hassan",
    rating: 4,
    date: "2023-11-19",
    text: "Consistently good quality and service.",
  },
  {
    name: "Jamil Khan",
    rating: 5,
    date: "2023-11-18",
    text: "Perfect product that delivers outstanding results.",
  },
  {
    name: "Nasser Ahmed",
    rating: 4,
    date: "2023-11-17",
    text: "Good value for money with reliable features.",
  },
  {
    name: "Sofia Ibrahim",
    rating: 5,
    date: "2023-11-16",
    text: "Absolutely fantastic quality and service.",
  },
  {
    name: "Rayan Hassan",
    rating: 4,
    date: "2023-11-15",
    text: "Solid performance with good functionality.",
  },
  {
    name: "Yara Omar",
    rating: 5,
    date: "2023-11-14",
    text: "Exceptional product that's worth every penny.",
  },
  {
    name: "Bassam Khan",
    rating: 4,
    date: "2023-11-13",
    text: "Good reliable product for everyday needs.",
  },
  {
    name: "Lara Abdullah",
    rating: 5,
    date: "2023-11-12",
    text: "Outstanding quality and exceptional performance.",
  },
  {
    name: "Zakaria Hassan",
    rating: 4,
    date: "2023-11-11",
    text: "Consistently good with minor enhancements.",
  },
  {
    name: "Maya Omar",
    rating: 5,
    date: "2023-11-10",
    text: "Perfect in every aspect. Very happy!",
  },
  {
    name: "Tariq Khan",
    rating: 4,
    date: "2023-11-09",
    text: "Good product that meets requirements well.",
  },
  {
    name: "Nada Hassan",
    rating: 5,
    date: "2023-11-08",
    text: "Exceptional value and premium quality.",
  },
  {
    name: "Khalil Omar",
    rating: 4,
    date: "2023-11-07",
    text: "Solid performance with reliable features.",
  },
  {
    name: "Rana Khan",
    rating: 5,
    date: "2023-11-06",
    text: "Absolutely brilliant! Highly recommended.",
  },
  {
    name: "Saif Hassan",
    rating: 4,
    date: "2023-11-05",
    text: "Good product with consistent quality.",
  },
  {
    name: "Dina Omar",
    rating: 5,
    date: "2023-11-04",
    text: "Exceptional performance and outstanding value.",
  },
  {
    name: "Amir Khan",
    rating: 4,
    date: "2023-11-03",
    text: "Reliable product that delivers good results.",
  },
  {
    name: "Laila Hassan",
    rating: 5,
    date: "2023-11-02",
    text: "Perfect quality that exceeds expectations.",
  },
  {
    name: "Walid Omar",
    rating: 4,
    date: "2023-11-01",
    text: "Good product with minor room for improvement.",
  },
  {
    name: "Nadia Khan",
    rating: 5,
    date: "2023-10-31",
    text: "Exceptional product with brilliant features.",
  },
  {
    name: "Faris Hassan",
    rating: 4,
    date: "2023-10-30",
    text: "Solid performance and good build quality.",
  },
  {
    name: "Rima Omar",
    rating: 5,
    date: "2023-10-29",
    text: "Absolutely love it! Worth the investment.",
  },
  {
    name: "Samar Khan",
    rating: 4,
    date: "2023-10-28",
    text: "Good reliable product for regular use.",
  },
  {
    name: "Talal Hassan",
    rating: 5,
    date: "2023-10-27",
    text: "Outstanding quality and exceptional service.",
  },
  {
    name: "Hala Omar",
    rating: 4,
    date: "2023-10-26",
    text: "Consistently good with reliable performance.",
  },
  {
    name: "Younis Khan",
    rating: 5,
    date: "2023-10-25",
    text: "Perfect product that delivers excellent results.",
  },
  {
    name: "Mona Hassan",
    rating: 4,
    date: "2023-10-24",
    text: "Good value proposition with solid features.",
  },
  {
    name: "Rashid Omar",
    rating: 5,
    date: "2023-10-23",
    text: "Exceptional performance and premium quality.",
  },
  {
    name: "Sana Khan",
    rating: 4,
    date: "2023-10-22",
    text: "Reliable product that meets expectations.",
  },
  {
    name: "Bader Hassan",
    rating: 5,
    date: "2023-10-21",
    text: "Absolutely brilliant in every way!",
  },
  {
    name: "Nour Omar",
    rating: 4,
    date: "2023-10-20",
    text: "Good product with consistent performance.",
  },
  {
    name: "Karim Khan",
    rating: 5,
    date: "2023-10-19",
    text: "Exceptional value and outstanding quality.",
  },
  {
    name: "Lina Hassan",
    rating: 4,
    date: "2023-10-18",
    text: "Solid build with reliable functionality.",
  },
  {
    name: "Omar Khan",
    rating: 5,
    date: "2023-10-17",
    text: "Perfect product that exceeds all expectations.",
  },
  {
    name: "Rana Hassan",
    rating: 4,
    date: "2023-10-16",
    text: "Good reliable product for daily needs.",
  },
  {
    name: "Zain Omar",
    rating: 5,
    date: "2023-10-15",
    text: "Exceptional performance and brilliant features.",
  },
  {
    name: "Huda Khan",
    rating: 4,
    date: "2023-10-14",
    text: "Consistently good with minor improvements.",
  },
  {
    name: "Yasser Hassan",
    rating: 5,
    date: "2023-10-13",
    text: "Absolutely fantastic quality and service.",
  },
  {
    name: "Nada Omar",
    rating: 4,
    date: "2023-10-12",
    text: "Good product that delivers as promised.",
  },
  {
    name: "Sagar Aryal",
    rating: 5,
    date: "2024-01-15",
    text: "Smooth booking process and breathtaking views from the top! Worth every dirham.",
  },
  {
    name: "Marvilous Cataluna",
    rating: 4,
    date: "2024-01-14",
    text: "Easy online ticket purchase. The view was amazing but quite crowded.",
  },
  {
    name: "Abishek Helmu",
    rating: 5,
    date: "2024-01-13",
    text: "Fast and efficient ticket booking. The sunset view was absolutely magical!",
  },
  {
    name: "Htet Htet Aung",
    rating: 4,
    date: "2024-01-12",
    text: "Good ticket prices and convenient time slots. Security check was a bit slow.",
  },
  {
    name: "Jissa Varghese",
    rating: 5,
    date: "2024-01-11",
    text: "Excellent mobile ticket system. No queues, straight to the elevators!",
  },
  {
    name: "Roxanne Gonsalves",
    rating: 4,
    date: "2024-01-10",
    text: "Reasonable pricing and good availability. The observation deck was packed.",
  },
  {
    name: "Jagath Chandra",
    rating: 5,
    date: "2024-01-09",
    text: "Perfect booking experience with instant confirmation. View worth the price!",
  },
  {
    name: "Sergio Kutovyi",
    rating: 4,
    date: "2024-01-08",
    text: "Easy to book online, but time slots fill up quickly. Plan in advance.",
  },
  {
    name: "Eiman Alkatheeri",
    rating: 5,
    date: "2024-01-07",
    text: "Flawless ticket purchase and unforgettable experience at the top!",
  },
  {
    name: "Ahmed Hassan",
    rating: 4,
    date: "2024-01-06",
    text: "Good value for money. The digital tickets made entry very convenient.",
  },
  {
    name: "Fatima Almeida",
    rating: 5,
    date: "2024-01-05",
    text: "Quick booking and spectacular views! Best attraction in Dubai.",
  },
  {
    name: "Mohammed Rahman",
    rating: 4,
    date: "2024-01-04",
    text: "Smooth ticket process but recommend booking sunset slots early.",
  },
  {
    name: "Aisha Khan",
    rating: 5,
    date: "2024-01-03",
    text: "Excellent service from booking to entry. The view is priceless!",
  },
  {
    name: "Omar Farooq",
    rating: 4,
    date: "2024-01-02",
    text: "Convenient online booking. Crowd management could be better.",
  },
  {
    name: "Zainab Ibrahim",
    rating: 5,
    date: "2024-01-01",
    text: "Perfect New Year's Eve booking! Well organized and spectacular.",
  },
  {
    name: "Khalid Mahmood",
    rating: 4,
    date: "2023-12-31",
    text: "Good ticket options available. The fast track was worth the extra cost.",
  },
  {
    name: "Layla Abdullah",
    rating: 5,
    date: "2023-12-30",
    text: "Effortless booking and breathtaking panoramic views of Dubai!",
  },
  {
    name: "Yusuf Ahmed",
    rating: 4,
    date: "2023-12-29",
    text: "Reasonable prices for this iconic experience. Book in advance.",
  },
  {
    name: "Noura Hassan",
    rating: 5,
    date: "2023-12-28",
    text: "Super easy ticket purchase and the view exceeded all expectations!",
  },
  {
    name: "Tariq Malik",
    rating: 4,
    date: "2023-12-27",
    text: "Good booking system but time slots are limited during peak season.",
  },
  {
    name: "Samira Khan",
    rating: 5,
    date: "2023-12-26",
    text: "Perfect Christmas visit! Tickets were reasonably priced and view amazing.",
  },
  {
    name: "Rashid Ali",
    rating: 4,
    date: "2023-12-25",
    text: "Easy online reservation. The elevator ride itself was an experience!",
  },
  {
    name: "Amira Said",
    rating: 5,
    date: "2023-12-24",
    text: "Excellent customer service and seamless ticket booking process.",
  },
  {
    name: "Jamal Hussein",
    rating: 4,
    date: "2023-12-23",
    text: "Good value ticket packages available. The view is worth it.",
  },
  {
    name: "Salma Abadi",
    rating: 5,
    date: "2023-12-22",
    text: "Quick and easy ticket purchase. The sunset view was unforgettable!",
  },
  {
    name: "Bilal Omar",
    rating: 4,
    date: "2023-12-21",
    text: "Convenient mobile tickets. Recommend the 'At the Top' experience.",
  },
  {
    name: "Hana Mohamed",
    rating: 5,
    date: "2023-12-20",
    text: "Perfect booking experience and the view from 124th floor stunning!",
  },
  {
    name: "Karim Abdullah",
    rating: 4,
    date: "2023-12-19",
    text: "Smooth ticket process but arrive early to avoid long queues.",
  },
  {
    name: "Leila Hassan",
    rating: 5,
    date: "2023-12-18",
    text: "Excellent online booking system with instant confirmation.",
  },
  {
    name: "Nasir Khan",
    rating: 4,
    date: "2023-12-17",
    text: "Good ticket prices for families. Children enjoyed the experience.",
  },
  {
    name: "Yasmin Ali",
    rating: 5,
    date: "2023-12-16",
    text: "Fast and efficient ticket booking. The view is absolutely worth it!",
  },
  {
    name: "Faisal Rahman",
    rating: 4,
    date: "2023-12-15",
    text: "Easy to book online but time slots get filled quickly.",
  },
  {
    name: "Dalia Ibrahim",
    rating: 5,
    date: "2023-12-14",
    text: "Perfect birthday visit! Ticket booking was smooth and easy.",
  },
  {
    name: "Hamza Ahmed",
    rating: 4,
    date: "2023-12-13",
    text: "Reasonable pricing for this iconic landmark experience.",
  },
  {
    name: "Nadia Said",
    rating: 5,
    date: "2023-12-12",
    text: "Excellent ticket service and the view was beyond expectations!",
  },
  {
    name: "Rami Hassan",
    rating: 4,
    date: "2023-12-11",
    text: "Good online booking platform. The fast track ticket is recommended.",
  },
  {
    name: "Sana Khan",
    rating: 5,
    date: "2023-12-10",
    text: "Seamless ticket purchase and unforgettable Dubai skyline views!",
  },
  {
    name: "Waleed Omar",
    rating: 4,
    date: "2023-12-09",
    text: "Convenient booking process. Sunset time slots are most popular.",
  },
  {
    name: "Lina Abdullah",
    rating: 5,
    date: "2023-12-08",
    text: "Perfect organization from ticket purchase to entry. Highly recommend!",
  },
  {
    name: "Adnan Malik",
    rating: 4,
    date: "2023-12-07",
    text: "Good ticket options. The view is spectacular especially at night.",
  },
  {
    name: "Mona Hassan",
    rating: 5,
    date: "2023-12-06",
    text: "Excellent booking experience and the panoramic view was breathtaking!",
  },
  {
    name: "Tahir Ahmed",
    rating: 4,
    date: "2023-12-05",
    text: "Easy ticket reservation system. Recommend booking in advance.",
  },
  {
    name: "Rania Khan",
    rating: 5,
    date: "2023-12-04",
    text: "Fast and efficient ticket service. The experience was worth every penny!",
  },
  {
    name: "Zayed Ibrahim",
    rating: 4,
    date: "2023-12-03",
    text: "Good value for money. The digital tickets made entry smooth.",
  },
  {
    name: "Nabil Hassan",
    rating: 5,
    date: "2023-12-02",
    text: "Perfect booking process and the view from top was incredible!",
  },
  {
    name: "Farah Omar",
    rating: 4,
    date: "2023-12-01",
    text: "Convenient online ticket purchase. Crowd management was good.",
  },
  {
    name: "Samir Khan",
    rating: 5,
    date: "2023-11-30",
    text: "Excellent ticket service and the Dubai fountain view was amazing!",
  },
  {
    name: "Lamia Ahmed",
    rating: 4,
    date: "2023-11-29",
    text: "Smooth booking experience. The observation deck was well maintained.",
  },
  {
    name: "Kareem Abdullah",
    rating: 5,
    date: "2023-11-28",
    text: "Perfect ticket booking and the sunset experience was magical!",
  },
  {
    name: "Salim Hassan",
    rating: 4,
    date: "2023-11-27",
    text: "Good ticket prices. The fast track option saved us a lot of time.",
  },
  {
    name: "Noor Khan",
    rating: 5,
    date: "2023-11-26",
    text: "Excellent online booking system with multiple payment options.",
  },
  {
    name: "Majid Omar",
    rating: 4,
    date: "2023-11-25",
    text: "Easy ticket reservation. The view is worth the ticket price.",
  },
  {
    name: "Sahar Ibrahim",
    rating: 5,
    date: "2023-11-24",
    text: "Perfect visit! Ticket booking was hassle-free and view spectacular.",
  },
  {
    name: "Anwar Hassan",
    rating: 4,
    date: "2023-11-23",
    text: "Good booking platform. Recommend the premium experience tickets.",
  },
  {
    name: "Hassan Khan",
    rating: 5,
    date: "2023-11-22",
    text: "Excellent service from start to finish. The view is unforgettable!",
  },
  {
    name: "Rasha Abdullah",
    rating: 4,
    date: "2023-11-21",
    text: "Convenient mobile ticket system. The elevator ride was impressive.",
  },
  {
    name: "Fahad Omar",
    rating: 5,
    date: "2023-11-20",
    text: "Perfect booking experience and the panoramic view was stunning!",
  },
  {
    name: "Mariam Hassan",
    rating: 4,
    date: "2023-11-19",
    text: "Good ticket options for different time slots. Book early.",
  },
  {
    name: "Jamil Khan",
    rating: 5,
    date: "2023-11-18",
    text: "Excellent ticket service and the Dubai skyline view was breathtaking!",
  },
  {
    name: "Nasser Ahmed",
    rating: 4,
    date: "2023-11-17",
    text: "Smooth online booking process. The view is worth every dirham.",
  },
  {
    name: "Sofia Ibrahim",
    rating: 5,
    date: "2023-11-16",
    text: "Perfect anniversary visit! Ticket booking was quick and easy.",
  },
  {
    name: "Rayan Hassan",
    rating: 4,
    date: "2023-11-15",
    text: "Good value ticket packages. The observation deck was amazing.",
  },
  {
    name: "Yara Omar",
    rating: 5,
    date: "2023-11-14",
    text: "Excellent booking system and the sunset view was spectacular!",
  },
  {
    name: "Bassam Khan",
    rating: 4,
    date: "2023-11-13",
    text: "Easy ticket purchase online. Recommend the skip-the-line option.",
  },
  {
    name: "Lara Abdullah",
    rating: 5,
    date: "2023-11-12",
    text: "Perfect family visit! Tickets were reasonably priced.",
  },
  {
    name: "Zakaria Hassan",
    rating: 4,
    date: "2023-11-11",
    text: "Good booking experience. The view from top is must-see in Dubai.",
  },
  {
    name: "Maya Omar",
    rating: 5,
    date: "2023-11-10",
    text: "Excellent ticket service and the city view was absolutely amazing!",
  },
  {
    name: "Tariq Khan",
    rating: 4,
    date: "2023-11-09",
    text: "Convenient online reservation system. Time slots availability good.",
  },
  {
    name: "Nada Hassan",
    rating: 5,
    date: "2023-11-08",
    text: "Perfect booking process and the Dubai fountain show was fantastic!",
  },
  {
    name: "Khalil Omar",
    rating: 4,
    date: "2023-11-07",
    text: "Good ticket prices. The fast track ticket is worth the extra cost.",
  },
  {
    name: "Rana Khan",
    rating: 5,
    date: "2023-11-06",
    text: "Excellent online booking with instant confirmation. Highly recommend!",
  },
  {
    name: "Saif Hassan",
    rating: 4,
    date: "2023-11-05",
    text: "Smooth ticket purchase. The view is spectacular especially at sunset.",
  },
  {
    name: "Dina Omar",
    rating: 5,
    date: "2023-11-04",
    text: "Perfect visit experience! Ticket booking was seamless and easy.",
  },
  {
    name: "Amir Khan",
    rating: 4,
    date: "2023-11-03",
    text: "Good booking platform with multiple time slot options available.",
  },
  {
    name: "Laila Hassan",
    rating: 5,
    date: "2023-11-02",
    text: "Excellent ticket service and the panoramic view was breathtaking!",
  },
  {
    name: "Walid Omar",
    rating: 4,
    date: "2023-11-01",
    text: "Easy online reservation. Recommend booking for sunset time.",
  },
  {
    name: "Nadia Khan",
    rating: 5,
    date: "2023-10-31",
    text: "Perfect Halloween visit! Ticket booking was quick and efficient.",
  },
  {
    name: "Faris Hassan",
    rating: 4,
    date: "2023-10-30",
    text: "Good value for money. The digital tickets made entry very smooth.",
  },
  {
    name: "Rima Omar",
    rating: 5,
    date: "2023-10-29",
    text: "Excellent booking experience and the view was absolutely worth it!",
  },
  {
    name: "Samar Khan",
    rating: 4,
    date: "2023-10-28",
    text: "Convenient ticket purchase system. The observation deck was great.",
  },
  {
    name: "Talal Hassan",
    rating: 5,
    date: "2023-10-27",
    text: "Perfect ticket service and the Dubai skyline view was amazing!",
  },
  {
    name: "Hala Omar",
    rating: 4,
    date: "2023-10-26",
    text: "Good booking process. The fast track option saved us waiting time.",
  },
  {
    name: "Younis Khan",
    rating: 5,
    date: "2023-10-25",
    text: "Excellent online booking with multiple payment methods available.",
  },
  {
    name: "Mona Hassan",
    rating: 4,
    date: "2023-10-24",
    text: "Smooth ticket reservation. The view from 124th floor spectacular.",
  },
  {
    name: "Rashid Omar",
    rating: 5,
    date: "2023-10-23",
    text: "Perfect booking experience and the sunset view was unforgettable!",
  },
  {
    name: "Sana Khan",
    rating: 4,
    date: "2023-10-22",
    text: "Good ticket options for different budgets. Well organized.",
  },
  {
    name: "Bader Hassan",
    rating: 5,
    date: "2023-10-21",
    text: "Excellent ticket service and the panoramic view was breathtaking!",
  },
  {
    name: "Nour Omar",
    rating: 4,
    date: "2023-10-20",
    text: "Easy online booking. Recommend the premium experience tickets.",
  },
  {
    name: "Karim Khan",
    rating: 5,
    date: "2023-10-19",
    text: "Perfect visit! Ticket booking was hassle-free and view amazing.",
  },
  {
    name: "Lina Hassan",
    rating: 4,
    date: "2023-10-18",
    text: "Good booking system. The elevator ride to top was impressive.",
  },
  {
    name: "Omar Khan",
    rating: 5,
    date: "2023-10-17",
    text: "Excellent ticket service and the Dubai fountain view was fantastic!",
  },
  {
    name: "Rana Hassan",
    rating: 4,
    date: "2023-10-16",
    text: "Convenient mobile tickets. Time slot availability was good.",
  },
  {
    name: "Zain Omar",
    rating: 5,
    date: "2023-10-15",
    text: "Perfect booking process and the city view was absolutely stunning!",
  },
  {
    name: "Huda Khan",
    rating: 4,
    date: "2023-10-14",
    text: "Good value ticket packages. The observation deck was well maintained.",
  },
  {
    name: "Yasser Hassan",
    rating: 5,
    date: "2023-10-13",
    text: "Excellent online booking with instant confirmation. Highly recommended!",
  },
  {
    name: "Nada Omar",
    rating: 4,
    date: "2023-10-12",
    text: "Smooth ticket purchase experience. The view is worth every penny.",
  },
  {
    name: "Adbul Amanana",
    rating: 1,
    date: "2023-10-12",
    text: "Weather was baad",
  },
  {
    name: "Nada Hassan",
    rating: 2,
    date: "2023-10-12",
    text: "",
  },
  {
    name: "Adbul Hassan",
    rating: 2,
    date: "2023-10-12",
    text: "",
  },
  {
    name: "Adbul Amanana",
    rating: 2,
    date: "2023-10-12",
    text: "Weather was baad",
  },
];
